<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('tanks', function (Blueprint $table) {
            $table->id();
            $table->string('tank_name');
            
        });

        // Insert the provided provinces
        $tanks = [
            "Manankattiya"
            ,"Nika wewa"
            ,"Kuda Halmilla Wewa"
            ,"Moragassegama wewa"
            ,"Duminnegama Wewa"
            ,"Randenigama Wewa"
            ,"Karambankulama Wewa"
            ,"Kuda Wewa"
            ,"Linda Wewa Maha Wewa"
            ,"Kuda Wewa"
            ,"Medawachchiya"
            ,"Sangilikanadarawa"
            ,"Puleliya maha wewa"
            ,"Nawakkulama Wewa"
            ,"Siyabalagas Wewa"
            ,"Poonewa Maha Wewa"
            ,"Kuda Puliyankulama Wewa"
            ,"Pinchikuda Wewa"
            ,"Dachchidamana Wewa/Probodagama Wewa"
            ,"Mahakumbukgollewa Wewa"
            ,"Maha Puliyankulama Wewa"
            ,"Kuda Palugollewa Wewa"
            ,"Pahalagama Wewa"
            ,"Galkande Wewa"
            ,"Bulupetha Wewa"
            ,"Kidawarankulama"
            ,"Kanugaha wewa"
            ," Kuda galenbidunu wewa"
            ,"Ambagaha wela wewa"
            ,"Galpothte gama wewa"
            ,"Pahala Moragollagama wewa"
            ,"Kawarakkulama"
            ,"Horiwila"
            ,"Kallanchiya"
            ,"Kapirikgama"
            ,"Pihimbiyagollewa"
            ,"Labunoruwa"
            ,"Siyabalawatta Maha Wewa"
            ,"Nawadalle"
            ,"Mahakuuratiheena Wewa"
            ,"Ilapaththagaha Wewa"
            ,"Mahathammannawa Wewa"
            ,"Mirisyaaya Wewa"
            ,"Madagama Ihala Wewa"
            ,"Ihala Paththinigama Wewa"
            ,"Kudathammannawa Wewa"
            ,"Pahala wagayamaduwa Wewa"
            ,"wagayamaduwa ihala amuna Wewa"
            ,"Ginigalwembu Wewa"
            ,"Weeragas Wewa"
            ,"Pahala boogaha Wewa"
            ,"Kotuwallewa Wewa"
            ,"Govi palliya Wewa"
            ,"Amunu Wewa"
            ,"Weera Wewa"
            ,"Damuna Amuna"
            ,"Wathupola Wewa"
            ,"Thoravatawana Wewa"
            ,"Monara Wewa"
            ,"Navatkuda Anicut"
            ,"Nedunkaraichchenai"
            ,"Koolankulam"
            ,"Sinna Chippikulam"
            ,"Kankankulam"
            ,"Kiristhavakulam"
            ,"Kunuvaikulam"
            ,"Musalkuththikkulam"
            ,"Karampaimadu"
            ,"Kalliyamurippukulam"
            ,"olumadukkulam"
            ,"Kurinchakulam"
            ,"Cheddikulam"
            ,"Mayilmuddiyiddakulam"
            ,"Periyapuliyalankulam"
            ,"Udaiyarkulam"
            ,"Illuppaikulam"
            ,"Periyakomarasankulam"
            ,"Periyakalveerankulam"
            ,"Asikulam"
            ,"Sinnakalveerankulam"
            ,"Kalnaddinakulam"
            ,"Pirappankulam"
            ,"Nochchikulam"
            ,"Tharanikulam"
            ,"Sinnakomarasankulam"
            ,"Niththikkulam"
            ,"Karunkalikkulam"
            ,"Kollankulam"
            ,"Kalukunnammaduwa"
            ,"Aluthgama Wewa"
            ,"Bakmeewewa mahawewa"
            ,"Bedigama Kuda Wewa"
            ,"Mahameruwa Wewa"
            ,"Bedigama Maha Wewa"
            ,"Angamale Wewa"
            ,"Hinguru Wewa"
            ,"Badalgama Wewa"
            ,"Kudagale Wewa"
            ,"Galapita Digana Wewa"
            ,"Etinimole Wewa"
            ,"Galketiyagama Wewa"
            ,"Wewgonna Wewa"
            ,"Rathmal Gaha Wewa"
            ,"Kon Wewa"
            ,"Ikiriwathtthe Gama Wewa"
            ,"Diul Wewa"
            ,"Lokurugama Wewa"
            ,"Demeda Diul wewa"
            ,"Kapugama Wewa"
            ,"Iahala Gama Wewa"
            ,"Andiyakotuwa wewa"
            ,"Gallewa wewa"
            ,"Kumbukwewa (sangappale)"
            ,"Horrow wewa (Sangappale)"
            ,"Perumbadayagama wewa"
            ,"Achiriya-Weliagara wewa"
            ,"Aththikulama wewa"
            ,"Amunukole wewa"
            ,"Nochchiyagama wewa"
            ,"Kumbuk wewa (Gampola)"
            ,"Diullegama wewa"
            ,"Maha Wewa"
            ,"Pothuwepitiya pahala wewa"
            ,"Meegahamula wewa"
            ,"Wathwathte Gama Wewa"
            ,"Galgiriyawa Wewa"
            ,"Wambotu Wewa"
            ,"Polgaha Wewa"
            ,"Dematagama Wewa"
            ,"Bora Wewa"
            ,"Thibbatuwawa Wewa"
            ,"Witharanagama Wewa"
            ,"Mapegamuwa Wewa"
            ,"Moragolla Gama Wewa"
            ,"Pansale Wewa"
            ,"Nika Wewa"
            ,"Paththinigama Wewa"
            ,"Pahala Alawththa Wewa"
            ,"Thuvarankerni"
            ,"Nagathalvu"
            ,"Mullikandal"
            ,"Kilavanarkaddu"
            ,"Kandal"
            ,"Vannakulam"
            ,"S.P. Potkerni"
            ,"Karunkalaithalvu"
            ,"Sadayappan"
            ,"Palayadikulam"
            ,"Manalkulam"
            ,"p.p. potkerni"
            ,"Kondachchi"
            ,"Illanthaimoddai"
            ,"Illathaikulam"
            ,"Antonymelinchi"
            ,"Koolankulam"
            ,"Thandikulam"
            ,"Pandaraveli"
            ,"Maruthamadukulam"
            ,"Periya Koomankulam"
            ,"Kalnaddi"
            ,"Kathankulam"
            ,"Puthukamam"
            ,"Periya thethakkuli"
            ,"Purandiveli"
            ,"Pethankulam"
            ,"Vempadikulam" 
            ,"Kanakanveli"
            ,"Vannakulam"
            ,"Theppukulama Tank"
            ,"Bakmeegolla Anicut"
            ,"Mathalapitiya Tank"
            ,"Paragahamadiththa Anicut"
            ,"Ange Anicut"

        ];


        foreach ($tanks as $tank) {
            DB::table('tanks')->insert(['tank_name' => $tank]);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('tanks');
    }
};
